templates:
    -
        path: "NSCmsBundle:Pages:page_index.html.twig"
        title: "Шаблон для главной страницы"
        default: false
        areas:
            -
                name: menu
                title: "Панель меню"
                fixed: true
            -
                name: content
                title: "Область контента"
            -
                name: feedback
                title: "Форма заявки"
            -
                name: right
                title: "Правая область"
            -
                name: skills
                title: "Что мы умеем?"
    -
        path: "NSCmsBundle:Pages:page.html.twig"
        title: "Шаблон страницы сайта"
        default: true
        areas:
            -
                name: sidebar
                title: "Боковая панель меню"
                fixed: true
            -
                name: content
                title: "Область контента"
